"""schema-v1: instruments, bars, ideas, portfolio, risk

Revision ID: 138d85fbc42e
Revises: 
Create Date: 2026-07-29 12:49:27.799357
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '138d85fbc42e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('broker', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('circuit', sa.String(length=16), nullable=False),
    sa.Column('equity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('free_margin', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("circuit IN ('investment','risk')", name=op.f('ck_accounts_circuit_known')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('broker', 'external_id', name='uq_accounts_broker')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_time', 'audit_events', ['occurred_at'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('strategy', sa.String(length=24), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=False),
    sa.Column('period_to', sa.Date(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('universe_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trades', sa.Integer(), nullable=False),
    sa.Column('net_return', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('expectancy_r', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('sharpe', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('sortino', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('calmar', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('brier_score', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('pbo', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('top5_contribution', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gate_passed', sa.Boolean(), nullable=False),
    sa.Column('gate_detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('period_to >= period_from', name=op.f('ck_backtest_runs_period_ordered')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_runs'))
    )
    op.create_table('data_quality_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('instrument_id', sa.String(length=64), nullable=True),
    sa.Column('flag', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_events'))
    )
    op.create_index('ix_dq_events_time', 'data_quality_events', ['occurred_at'], unique=False)
    op.create_table('instruments',
    sa.Column('instrument_id', sa.String(length=64), nullable=False),
    sa.Column('venue', sa.String(length=16), nullable=False),
    sa.Column('asset_class', sa.String(length=24), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('tick_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('quantity_step', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('min_quantity', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('min_notional', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('contract_multiplier', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('next_contract', sa.String(length=64), nullable=True),
    sa.Column('correlation_cluster', sa.String(length=32), nullable=True),
    sa.Column('is_tradable', sa.Boolean(), nullable=False),
    sa.Column('in_universe', sa.Boolean(), nullable=False),
    sa.Column('universe_note', sa.String(length=256), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('lot_size > 0', name=op.f('ck_instruments_lot_size_positive')),
    sa.CheckConstraint('quantity_step > 0', name=op.f('ck_instruments_quantity_step_positive')),
    sa.CheckConstraint('tick_size > 0', name=op.f('ck_instruments_tick_size_positive')),
    sa.CheckConstraint('tick_value > 0', name=op.f('ck_instruments_tick_value_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments')),
    sa.UniqueConstraint('instrument_id', name=op.f('uq_instruments_instrument_id'))
    )
    op.create_index('ix_instruments_universe', 'instruments', ['venue', 'in_universe'], unique=False)
    op.create_table('model_registry',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('algorithm', sa.String(length=48), nullable=False),
    sa.Column('trained_from', sa.Date(), nullable=False),
    sa.Column('trained_to', sa.Date(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('oos_brier', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('oos_ece', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('calibration_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_by_human', sa.Boolean(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("role IN ('champion','challenger','retired')", name=op.f('ck_model_registry_role_known')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_registry')),
    sa.UniqueConstraint('name', 'version', name='uq_model_registry_version')
    )
    op.create_table('portfolio_models',
    sa.Column('profile', sa.String(length=16), nullable=False),
    sa.Column('package', sa.String(length=16), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('expected_return_low', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('expected_return_high', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('target_volatility', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('model_drawdown_limit', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('cvar_95', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('stress_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('expected_return_high >= expected_return_low', name=op.f('ck_portfolio_models_return_band_ordered')),
    sa.CheckConstraint('valid_until > generated_at', name=op.f('ck_portfolio_models_model_expires_later')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_models'))
    )
    op.create_index('ix_portfolio_models_lookup', 'portfolio_models', ['profile', 'package', 'generated_at'], unique=False)
    op.create_table('risk_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('risk_equity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('open_risk', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('day_pnl_pct', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('week_pnl_pct', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('month_pnl_pct', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('current_drawdown', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('drawdown_multiplier', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('binding_limit', sa.String(length=16), nullable=False),
    sa.Column('entries_blocked', sa.Boolean(), nullable=False),
    sa.Column('halted', sa.Boolean(), nullable=False),
    sa.Column('cluster_risk_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_snapshots'))
    )
    op.create_index('ix_risk_snapshots_time', 'risk_snapshots', ['taken_at'], unique=False)
    op.create_table('risk_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_mode', sa.String(length=20), nullable=False),
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('kill_switch_reason', sa.Text(), nullable=False),
    sa.Column('halted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_risk_state_single_row')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_state'))
    )
    op.create_table('bars',
    sa.Column('instrument_id', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('high', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('low', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('close', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('volume_units', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('volume_notional', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('open_interest', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('quality_flags', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('high >= low', name=op.f('ck_bars_high_not_below_low')),
    sa.CheckConstraint('high >= open AND high >= close', name=op.f('ck_bars_high_is_max')),
    sa.CheckConstraint('low <= open AND low <= close', name=op.f('ck_bars_low_is_min')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], name=op.f('fk_bars_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'timeframe', 'open_time', name=op.f('pk_bars'))
    )
    op.create_index('ix_bars_lookup', 'bars', ['instrument_id', 'timeframe', 'open_time'], unique=False)
    op.create_table('holdings',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.String(length=64), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('market_price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('asset_class', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_holdings_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'instrument_id', 'as_of', name=op.f('pk_holdings'))
    )
    op.create_table('market_features',
    sa.Column('instrument_id', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('bar_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('atr', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('ema_fast', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('ema_slow', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('adx', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('rsi', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('volume_z', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('relative_volume', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('oi_change_z', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('funding_percentile', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('realized_volatility', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('atr_percentile', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('structure_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], name=op.f('fk_market_features_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'timeframe', 'bar_time', 'feature_version', name=op.f('pk_market_features'))
    )
    op.create_table('portfolio_weights',
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.String(length=64), nullable=False),
    sa.Column('asset_class', sa.String(length=24), nullable=False),
    sa.Column('target_weight', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('kill_conditions', sa.Text(), nullable=False),
    sa.Column('score', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('expected_return', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.CheckConstraint('target_weight >= 0 AND target_weight <= 1', name=op.f('ck_portfolio_weights_weight_is_ratio')),
    sa.ForeignKeyConstraint(['model_id'], ['portfolio_models.id'], name=op.f('fk_portfolio_weights_model_id_portfolio_models'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_id', 'instrument_id', name=op.f('pk_portfolio_weights'))
    )
    op.create_table('rebalance_drafts',
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('trigger_reason', sa.String(length=64), nullable=False),
    sa.Column('actions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_costs', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('estimated_tax', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('tax_is_estimate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['portfolio_models.id'], name=op.f('fk_rebalance_drafts_model_id_portfolio_models'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rebalance_drafts'))
    )
    op.create_table('regime_snapshots',
    sa.Column('instrument_id', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('bar_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trend', sa.String(length=16), nullable=False),
    sa.Column('trend_score', sa.Integer(), nullable=False),
    sa.Column('volatility', sa.String(length=16), nullable=False),
    sa.Column('liquidity', sa.String(length=16), nullable=False),
    sa.Column('derivatives_flow', sa.String(length=20), nullable=False),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('trend_score BETWEEN -5 AND 5', name=op.f('ck_regime_snapshots_trend_score_in_range')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], name=op.f('fk_regime_snapshots_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'timeframe', 'bar_time', name=op.f('pk_regime_snapshots'))
    )
    op.create_table('trade_ideas',
    sa.Column('instrument_id', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=24), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('quality_status', sa.String(length=12), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('context_timeframe', sa.String(length=8), nullable=False),
    sa.Column('setup_timeframe', sa.String(length=8), nullable=False),
    sa.Column('trigger_timeframe', sa.String(length=8), nullable=False),
    sa.Column('order_intent', sa.String(length=24), nullable=False),
    sa.Column('entry_low', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('entry_high', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('entry_reference', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('stop', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('tp1', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('tp2', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('tp3', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('invalidation', sa.Text(), nullable=False),
    sa.Column('rr_tp1', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('rr_tp2', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('score', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('data_quality', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('p_tp1_before_sl', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('p_tp2_before_sl', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('p_positive_r_after_costs', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('expected_r', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('probability_source', sa.String(length=48), nullable=False),
    sa.Column('risk_pct', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('risk_amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('risk_per_unit', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('correlation_cluster', sa.String(length=32), nullable=True),
    sa.Column('drawdown_multiplier', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('explanation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_warnings', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('signal_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('was_presented', sa.Boolean(), nullable=False),
    sa.Column('presentation_rank', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.CheckConstraint("(direction = 'LONG' AND stop < entry_low) OR (direction = 'SHORT' AND stop > entry_high)", name=op.f('ck_trade_ideas_stop_on_correct_side')),
    sa.CheckConstraint("(direction = 'LONG' AND tp1 > entry_high AND tp2 > tp1) OR (direction = 'SHORT' AND tp1 < entry_low AND tp2 < tp1)", name=op.f('ck_trade_ideas_targets_ordered_by_direction')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_trade_ideas_confidence_is_ratio')),
    sa.CheckConstraint('data_quality > 0 AND data_quality <= 1', name=op.f('ck_trade_ideas_data_quality_is_ratio')),
    sa.CheckConstraint('entry_high >= entry_low', name=op.f('ck_trade_ideas_entry_band_ordered')),
    sa.CheckConstraint('expires_at > signal_time', name=op.f('ck_trade_ideas_expiry_after_signal')),
    sa.CheckConstraint('p_tp1_before_sl >= 0 AND p_tp1_before_sl <= 1', name=op.f('ck_trade_ideas_p_tp1_is_probability')),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_trade_ideas_quantity_not_negative')),
    sa.CheckConstraint('score >= 0 AND score <= 100', name=op.f('ck_trade_ideas_score_in_range')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], name=op.f('fk_trade_ideas_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_ideas'))
    )
    op.create_index('ix_ideas_instrument', 'trade_ideas', ['instrument_id', 'signal_time'], unique=False)
    op.create_index('ix_ideas_status', 'trade_ideas', ['status', 'signal_time'], unique=False)
    op.create_table('idea_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('old_status', sa.String(length=24), nullable=True),
    sa.Column('new_status', sa.String(length=24), nullable=False),
    sa.Column('reason_code', sa.String(length=48), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=False),
    sa.Column('market_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('probability_before', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('probability_after', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('user_action', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['trade_ideas.id'], name=op.f('fk_idea_events_idea_id_trade_ideas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idea_events')),
    sa.UniqueConstraint('idea_id', 'sequence', name='uq_idea_events_sequence')
    )
    op.create_index('ix_idea_events_time', 'idea_events', ['occurred_at'], unique=False)
    op.create_table('idea_outcomes',
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('barrier_outcome', sa.String(length=12), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bars_to_resolution', sa.Integer(), nullable=True),
    sa.Column('model_r', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('ideal_r', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('actual_r', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('actual_pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('mae_r', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('mfe_r', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('entry_slippage', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('exit_slippage', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('fees', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('funding', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('label_usable', sa.Boolean(), nullable=False),
    sa.Column('detail_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['trade_ideas.id'], name=op.f('fk_idea_outcomes_idea_id_trade_ideas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('idea_id', name=op.f('pk_idea_outcomes'))
    )
    op.create_table('idea_skips',
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=24), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('skipped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['trade_ideas.id'], name=op.f('fk_idea_skips_idea_id_trade_ideas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('idea_id', name=op.f('pk_idea_skips'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idea_skips')
    op.drop_table('idea_outcomes')
    op.drop_index('ix_idea_events_time', table_name='idea_events')
    op.drop_table('idea_events')
    op.drop_index('ix_ideas_status', table_name='trade_ideas')
    op.drop_index('ix_ideas_instrument', table_name='trade_ideas')
    op.drop_table('trade_ideas')
    op.drop_table('regime_snapshots')
    op.drop_table('rebalance_drafts')
    op.drop_table('portfolio_weights')
    op.drop_table('market_features')
    op.drop_table('holdings')
    op.drop_index('ix_bars_lookup', table_name='bars')
    op.drop_table('bars')
    op.drop_table('risk_state')
    op.drop_index('ix_risk_snapshots_time', table_name='risk_snapshots')
    op.drop_table('risk_snapshots')
    op.drop_index('ix_portfolio_models_lookup', table_name='portfolio_models')
    op.drop_table('portfolio_models')
    op.drop_table('model_registry')
    op.drop_index('ix_instruments_universe', table_name='instruments')
    op.drop_table('instruments')
    op.drop_index('ix_dq_events_time', table_name='data_quality_events')
    op.drop_table('data_quality_events')
    op.drop_table('backtest_runs')
    op.drop_index('ix_audit_events_time', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('accounts')
    # ### end Alembic commands ###
